python main.py \
    --epochs 300 \
    --num_clients 50 \
    --clients_percent 0.4 \
    --pre_train 'False' \
    --model 'AlexNet' \
    --dataset "cifar10" \
    --num_classes 10 \
    --image_size 32 \
    --gpu 7 \
    --seed 1 \
    --save_dir "./result/AlexNet/" \
    --embed_layer_names "extractor.bn3;extractor.bn4;extractor.bn5" \
    --test_interval 10
